### ISSUE TITLE
CACHEING ISSUE

### ISSUE THREAD

**Issue by scargill** [tzapu/node-red-contrib-blynk#11]
Got a definite issue here...   so - add a WRITE EVENT NODE.... button on the APP - say, on V1.  So you have a button that when pressed sends out a signal to node-red.

Copy the button - PASTE - change V1 to V2.   Add another button to your APP. You now have TWO buttons - one for ON (say), one for OFF.

Press on - the light comes on and immediately goes off. Until you REBOOT Node-Red, it seems unaware that you have changed the virtual input on the second (or third) input.

This needs fixing - rebooting Node-Red every time you add something is not good.

I think I had a similar issue when adding a second APP KEY.. again for it to work - I had to reboot node-red..

**Comment by tzapu** [comment]
hi, thanks for reporting, will try to take a look at it asap

**Comment by tzapu** [comment]
hi, i ve tried the above but can't seem to replicate.
I have tried with both write events and write commands like so:
https://www.dropbox.com/s/p7y76tnsdps5oud/Screenshot%202015-11-05%2009.12.52.png?dl=0
after adding each one i deployed in FULL mode and sent a command. I have copied each node from the other, **are you using partial deploy? did not test that**.
2 buttons and 2 value displays in the app and they seem to receive and send properly on their respective pin. I setup the interface previously to setting up node red, don t know if it matters.

**Comment by Toshibass** [comment]
I see the same same behaviour if I add a new node the screen cannot connect unless node-red is rebooted, also since the recent updates to the blynk library everything went smooth with no error messages, but I notice since updating node-red to 0.12 release this has re-appeared

pi@raspberrypi ~ $ (node) warning: possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at MqttClient.addListener (events.js:179:15)
    at MqttClient.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/io/10-mqtt.js:164:41)
    at MqttClient.emit (events.js:129:20)
    at MqttClient._handleConnack (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:667:10)
    at MqttClient._handlePacket (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:271:12)
    at process (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:218:12)
    at Writable.writable._write (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:228:5)
    at doWrite (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)

**Comment by tzapu** [comment]
hi, that warning seems to be in mqtt nodes not in the blynk ones

**Comment by tzapu** [comment]
@Toshibass are you using full or partial deploy?

**Comment by Toshibass** [comment]
Yes your right I didn't see that until you said I guess that's because I was so used to seeing that for Blynk, ok I will take it up on the node-red group.

Re your question ...  Full Deploy.
