### ISSUE TITLE
Does not recover when internet goes down

### ISSUE THREAD

**Issue by alport** [tzapu/node-red-contrib-blynk#22]
This may or may not be related to the two previous "Does not recover issues".
When the internet goes down I get an "Uncaught Exception". 
My retreat is in the mountains which does not have a reliable internet connection!
I can sometimes recover by stopping and restarting node-red.
I am keen to persevere with this Blynk node in node-red because; the widgets are beautiful, it gives iOS cloud UI access and any data configuration can be accommodated by node-red.

Specifically, the error dialog is:
pi@RPi40:~ $ node-red-start
Once Node-RED has started, point a browser at http://192.168.1.102:1880
To stop Node-RED use the command   node-red-stop
[ ok ] Starting nodered (via systemctl): nodered.service.
28 Dec 15:17:29 - [info] Server now running at http://127.0.0.1:1880/
28 Dec 15:17:29 - [info] Starting flows
Connecting to SSL: cloud.blynk.cc 8441
28 Dec 15:17:29 - [info] Started flows
Connecting to SSL: cloud.blynk.cc 8441
Connecting to SSL: cloud.blynk.cc 8441
28 Dec 15:17:44 - [red] Uncaught Exception:
28 Dec 15:17:44 - Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete](dns.js:124:16)

**Comment by tzapu** [comment]
Hi, that error is somewhere lower layer than node red or blynk contrib.
Could you give it a test without ssl to see if it better behaved?
Cheers
